# numpy inf和nan

In [1]:
'''
C 语言中表示最大的正整数值是 0x7FFF FFFF，最小的负整数是 0x8000 0000。
查阅资料后，发现 inf 表示无穷大，需要使用 float(‘inf’) 函数来转化，那么对应的就有	float('-inf') 表示无穷小了。
这样你就可以使用任意数来判断和它的关系了。
那什么时候会出现inf呢？ 比如一个数字除以0，Python中会报错，但是numpy中会是一个inf或者-inf
另外还有 nan，这种写法在 pandans 中常见，表示缺失的数据，所以一般用 nan 来表示。任何与其做运算结果都是 nan
'''
import numpy as np
#nan 是not a number的缩写，表示非数字，在numpy中表示一个非数字值，可以用来表示缺失数据
# 创建一个nan和inf #
a = np.nan
b = np.inf
print(a, type(a))
print(b, type(b))

nan <class 'float'>
inf <class 'float'>


In [2]:
# 并 且  np.nan != np.nan	结果 是TRUE
# 所以我们可以使用这两个结合使用判断nan的个数
print(np.nan == np.nan)
print(True == 1)
print(False == 0)
np.nan + 1  #n

False
True
True


nan

In [2]:
# --判断数组中为nan的个数
t = np.arange(24, dtype=float).reshape(4, 6)

# 将三行四列的数改成nan
t[3, 4] = np.nan
t[2, 4] = np.nan
print(t)


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. nan 17.]
 [18. 19. 20. 21. nan 23.]]


In [4]:
# 可以使用np.count_nonzero() 来判断非零的个数
# print(np.count_nonzero(t))
print(t != t)
print('-' * 50)
print(np.count_nonzero(t != t))  # 统计nan的个数


[[False False False False False False]
 [False False False False False False]
 [False False False False  True False]
 [False False False False  True False]]
--------------------------------------------------
22


In [5]:
# 将nan替换为0
t[np.isnan(t)] = 0
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15.  0. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [6]:
# ----------练习： 处理数组中nan
t = np.arange(24).reshape(4, 6).astype('float')
#
# 将数组中的一部分替换nan
t[1, 3:] = np.nan
print(t)
print('-------------------')
print(t.shape)
print(id(t))
# 遍历每一列，然后判断每一列是否有nan
for i in range(t.shape[1]):
    #获取当前列数据
    temp_col = t[:, i]

    # 判断当前列的数据中是否含有nan
    nan_num = np.count_nonzero(temp_col != temp_col)
    # 条件成立说明含有nan
    if nan_num != 0:
        # 将这一列不为nan的数据拿出来,并计算平均值
        temp_col_not_nan = temp_col[temp_col == temp_col]
        print(temp_col_not_nan)
        # 将nan替换成这一列的平均值
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)

print(t)
print(id(t))

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
-------------------
(4, 6)
2534017860496
[ 3. 15. 21.]
[ 4. 16. 22.]
[ 5. 17. 23.]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
2534017860496


In [3]:
print(np.inf == np.inf)
np.inf

True


inf

In [4]:
# np.nan和任何数据运算的结果都是nan
t = np.arange(24).reshape(4, 6).astype('float')
#
# 将数组中的一部分替换nan
t[1, 3:] = np.nan

t1 = np.arange(24).reshape(4, 6).astype('float')
t + t1

array([[ 0.,  2.,  4.,  6.,  8., 10.],
       [12., 14., 16., nan, nan, nan],
       [24., 26., 28., 30., 32., 34.],
       [36., 38., 40., 42., 44., 46.]])

In [5]:
arr = np.array([-1, 0])
print(arr)
print(arr[0] / arr[1])  #1除0就会得到inf

[-1  0]
-inf


C:\Users\伞兵2号\AppData\Local\Temp\ipykernel_22284\773640058.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  print(arr[0] / arr[1])  #1除0就会得到inf


In [2]:
np.nan + np.inf

nan

# 转置和轴滚动

In [1]:
#对换数组的维度
import numpy as np

a = np.arange(12).reshape(3, 4)
print('原数组：')
print(a)
print('\n')

print('对换数组：')
print(np.transpose(a))
print(a)

# 与transpose一致
a = np.arange(12).reshape(3, 4)

print('原数组：')
print(a)
print('\n')

print('转置数组：')
print(a.T)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [7]:
# 函数用于交换数组的两个轴
t1 = np.arange(24).reshape(4, 6)
re1 = t1.swapaxes(1, 0)

print(' 原 数 组 ：')
print(t1)
print('\n')
print(re1.shape)
print('调用 swapaxes 函数后的数组：')
print(re1)

 原 数 组 ：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


(6, 4)
调用 swapaxes 函数后的数组：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [ ]:
t3 = np.arange(60).reshape(3, 4, 5)
print(t3.shape)
print('-' * 50)
t3 = np.swapaxes(t3, 1, 2)
print(t3.shape)
# print(t3) 数据不用记住，不用观察

In [ ]:
# 数组的轴滚动,swapaxes每次只能交换两个轴，没有rollaxis方便，默认情况下轴滚动最前面
a = np.ones((3, 4, 5, 6))
# np.rollaxis(a, 2).shape
np.rollaxis(a, 3, 1).shape

In [ ]:
#数据拷贝，copy()和赋值的区别
b = np.array([[1, 2, 3], [1, 2, 3]])
a = b.copy()
a

In [ ]:
b[0, 0] = 3
print(b)
a

In [ ]:
#随机数生成
arr = np.random.rand(2, 3, 4)
print(arr)

# Series

In [4]:
import pandas as pd


In [5]:
# 生成一个Series

ser_obj = pd.Series(range(10, 20)) #默认索引是0-9
print(ser_obj) #打印输出会带有类型

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64


In [6]:
print('-'*50)
# 获取数据
print(ser_obj.values)  #values实际是ndarray
print(type(ser_obj.values)) #类型是ndarray
# 获取索引
print(ser_obj.index)  #内部自带的类型--RangeIndex
ser_obj.dtype #数据类型

--------------------------------------------------
[10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=10, step=1)


dtype('int64')

In [7]:
print(ser_obj[0]) 
ser_obj[9] #
# 访问不存在的索引下标会报keyerror

10


np.int64(19)

In [ ]:
print(ser_obj * 2)  #元素级乘法
print(ser_obj > 15) #返回一个bool序列

In [ ]:
#字典变为series，索引是字典的key，value是字典的value，感受非默认索引

year_data = {2001: 17.8, 2005: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2)
print('-'*50)
print(ser_obj2.index)
print('-'*50)
print(ser_obj2[2001])
ser_obj2.values

In [ ]:
#有点鸡肋
print(ser_obj2.name) #Series名字
print(ser_obj2.index.name)  #索引名字
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year1'
print('-'*50)
print(ser_obj2.head())  #head默认显示前5行


# DataFrame

In [ ]:
import numpy as np

# 通过ndarray构建DataFrame
t = pd.DataFrame(np.arange(12).reshape((3,4))) #默认索引是0-2
print(t)
print('-'*50)


In [ ]:
array = np.random.randn(5,4)
print(array)
print('-'*50)
df_obj = pd.DataFrame(array)
print(df_obj.head()) #默认显示前5行

In [ ]:
t.loc[0] #单独把某一行取出来,类型是series

In [ ]:
# 列表套字典  变df
d2 =[{"name" : "xiaohong" ,"age" :32,"tel" :10010},
     { "name": "xiaogang" ,"tel": 10000} ,
     {"name":"xiaowang" ,"age":22}]
df6=pd.DataFrame(d2)
print(df6) #缺失值会用NaN填充
print(type(df6.values)) #ndarray

In [ ]:
pd.Series(1, index=list(range(3,7)),dtype='float32')

In [ ]:
#df中不同列可以是不同的数据类型,同一列必须是一个数据类型
import pandas as pd
import numpy as np
dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([1,2,3,4],dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'wangdao' }
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)

In [ ]:
print('-'*50)
print(df_obj2.index) #行索引,重点
#补课改变
# df_obj2.index[0]=2  不可以单独修改某个索引值
print(df_obj2.columns) #列索引，重点
df_obj2.dtypes #每一列的数据类型，重点

In [ ]:
# 感受日期,初始化df，设置行索引，列索引
dates = pd.date_range('20130101', periods=6) #默认freq='D'，即天
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print('-'*50)
print(df.index)

In [ ]:
#取数据
print(df_obj2)
print('-'*50)
print(type(df_obj2))
print('-'*50)
#pd中使用索引名来取某一行，或者列
print(df_obj2['B'])
print('-'*50)
#把df的某一列取出来是series
print(type(df_obj2['B']))

In [ ]:
#增加列数据，列名是自定义的
df_obj2['G'] = df_obj2['D'] + 4
print(df_obj2.head())

In [ ]:
# 删除列
del(df_obj2['G'])
print(df_obj2.head())

In [ ]:
import pandas as pd
import numpy as np
import random

In [ ]:
df_data = pd.DataFrame([np.random.randn(3), [1., 2., np.nan],
                       [np.nan, 4., np.nan], [1., 2., 3.]])
print(df_data.head())

In [ ]:
df_data.iloc[2,0]

In [ ]:
#isnull来判断是否有空的数据
print(df_data.isnull())

In [ ]:
#帮我计算df_data缺失率
print(df_data.isnull().sum()/len(df_data))

# 删除缺失数据

In [ ]:
#默认一个样本，任何一个特征缺失，就删除
#inplace True是修改的是原有的df
#subset=[0]是指按第一列来删除,第一列有空值就删除对应的行
print(df_data.dropna(subset=[0]))
# df_data

In [ ]:
df_data

In [ ]:
#用的不多，用在某个特征缺失太多时，才会进行删除
print(df_data.dropna(axis=1))  #某列由nan就删除该列

In [ ]:
df_data

## 填充缺失数据

In [ ]:
#均值，中位数，众数填充

In [ ]:
#给零列的空值填为-100，按特征（按列）去填充
print(df_data.iloc[:,0].fillna(-100.))
df_data

In [ ]:
#依次拿到每一列
for i in df_data.columns:
    print(df_data.loc[:,i])

In [ ]:
df_data.iloc[:,0].fillna(-100.,inplace=True) #inplace=True后面会被删除

In [ ]:
df_data.iloc[:,2]=df_data.iloc[:,2].fillna(df_data.iloc[:,2].mean()) #用均值填充空值

In [ ]:
df_data